name: bump-deps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # midnight UTC

jobs:
  molt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hasundue/molt-action@v1
